services:
  - type: web
    name: vietnamese-corpus-filter
    env: python
    buildCommand: pip install -r render-requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0